// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using cashierAPI.database;

#nullable disable

namespace cashierAPI.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("cashierAPI.Models.AkunCs", b =>
                {
                    b.Property<int>("id_akunCs")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("status")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("user_id")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("id_akunCs");

                    b.HasIndex("user_id")
                        .IsUnique();

                    b.ToTable("AkunCs");
                });

            modelBuilder.Entity("cashierAPI.Models.Closing", b =>
                {
                    b.Property<int>("id_closing")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("alamat_pegiriman")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("konsumen_id")
                        .HasColumnType("int");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<int>("total_harga")
                        .HasColumnType("int");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("variant_id")
                        .HasColumnType("int");

                    b.HasKey("id_closing");

                    b.HasIndex("konsumen_id");

                    b.HasIndex("variant_id");

                    b.ToTable("Closings");
                });

            modelBuilder.Entity("cashierAPI.Models.Konsumen", b =>
                {
                    b.Property<int>("id_Konsumen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("AkunCs_id")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("kontak")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("nama_konsumen")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id_Konsumen");

                    b.HasIndex("AkunCs_id")
                        .IsUnique();

                    b.ToTable("konsumens");
                });

            modelBuilder.Entity("cashierAPI.Models.Product", b =>
                {
                    b.Property<int>("id_product")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("deskripsi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("harga_satuan")
                        .HasColumnType("int");

                    b.Property<string>("jenis_product")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("nama_product")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("status")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("total_stok")
                        .HasColumnType("int");

                    b.HasKey("id_product");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("cashierAPI.Models.User", b =>
                {
                    b.Property<int>("id_user")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("alamat")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("gender")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("nama_user")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("no_telpon")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id_user");

                    b.ToTable("users");
                });

            modelBuilder.Entity("cashierAPI.Models.Variant", b =>
                {
                    b.Property<int>("id_variant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("expired_date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("harga_tambahan")
                        .HasColumnType("int");

                    b.Property<string>("keterangan")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("nama_variant")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("product_id")
                        .HasColumnType("int");

                    b.Property<int>("stok")
                        .HasColumnType("int");

                    b.HasKey("id_variant");

                    b.HasIndex("product_id");

                    b.ToTable("Variants");
                });

            modelBuilder.Entity("cashierAPI.Models.AkunCs", b =>
                {
                    b.HasOne("cashierAPI.Models.User", "User")
                        .WithOne("AkunCs")
                        .HasForeignKey("cashierAPI.Models.AkunCs", "user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("cashierAPI.Models.Closing", b =>
                {
                    b.HasOne("cashierAPI.Models.Konsumen", "konsumen")
                        .WithMany("Closings")
                        .HasForeignKey("konsumen_id");

                    b.HasOne("cashierAPI.Models.Variant", "variant")
                        .WithMany("closings")
                        .HasForeignKey("variant_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("konsumen");

                    b.Navigation("variant");
                });

            modelBuilder.Entity("cashierAPI.Models.Konsumen", b =>
                {
                    b.HasOne("cashierAPI.Models.AkunCs", "AkunCs")
                        .WithOne("Konsumen")
                        .HasForeignKey("cashierAPI.Models.Konsumen", "AkunCs_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AkunCs");
                });

            modelBuilder.Entity("cashierAPI.Models.Variant", b =>
                {
                    b.HasOne("cashierAPI.Models.Product", "product")
                        .WithMany("variants")
                        .HasForeignKey("product_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("product");
                });

            modelBuilder.Entity("cashierAPI.Models.AkunCs", b =>
                {
                    b.Navigation("Konsumen");
                });

            modelBuilder.Entity("cashierAPI.Models.Konsumen", b =>
                {
                    b.Navigation("Closings");
                });

            modelBuilder.Entity("cashierAPI.Models.Product", b =>
                {
                    b.Navigation("variants");
                });

            modelBuilder.Entity("cashierAPI.Models.User", b =>
                {
                    b.Navigation("AkunCs");
                });

            modelBuilder.Entity("cashierAPI.Models.Variant", b =>
                {
                    b.Navigation("closings");
                });
#pragma warning restore 612, 618
        }
    }
}
